name: Python y2b-map

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        repository: dd-center/y2b-map
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Update
      run: |
        python3 update_list.py
    - name: push
      uses: github-actions-x/commit@v2.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'vdb-bot'
        commit-message: 'vdb-update'
        force-add: 'true'
        files: map.csv
